fix to min range failing when you use no items
WeakAuras/LibRangeCheck-3.0 pull request #17
Opened 2024-03-01 15:48 UTC by kodewdle

- this implements the fix for https://github.com/WeakAuras/LibRangeCheck-3.0/issues/16 which happens when you call the lib with using `noItems` to handle Hunter, Warrior, and Rogue better with some of their MinRange spells.  it falls back to the interact state (allowing the spell min to pass for that spell, which may not be the intention, if you wanted range to fail within 8 for example on Hunter); ignoring its actual min range value but returning the actual range (the range number values returned are still correct as you get closer or go further away).

- this PR also improves the range returns for classes that do have min range spells by also including the interact returns; warriors only adding 1 interact return (to keep the return at distance of Charge at range 25, instead of Follow at range 28, unless they have Throw at range 30. `displayed in the video`)

- the video print statement includes the value of `#checkerList`, the `lo` value and its `info` of the spell being checked currently, and the `hi` value and its `range` value (in that order) for warrior on Classic PTR within function `getRangeWithCheckerList`

- this PR also includes a few tiny changes that don't change functionality (except for `FriendColor` and `HarmColor` actually existing) but it's something i had in our copy, i hope these can also be accepted so it's identical to the mainstream.

https://github.com/WeakAuras/LibRangeCheck-3.0/assets/2266754/75211612-d9a9-42b2-ab06-7f9413bca9a4

2024-03-01 18:30 UTC, ensey approved these changes
Works as intended - fixes known bug https://github.com/WeakAuras/LibRangeCheck-3.0/issues/16

2024-03-03 22:05 UTC, Stanzilla requested changes

2024-03-03 22:05 UTC, Stanzilla commented on LibRangeCheck-3.0/LibRangeCheck-3.0.lua
>  local MINOR_VERSION = 13
needs a version bump here

2024-03-03 22:05 UTC, Stanzilla commented on LibRangeCheck-3.0/LibRangeCheck-3.0.lua
> +
are you guys still using mik's globals script?

2024-03-05 16:43 UTC, Stanzilla commented
@InfusOnWoW found a few issues with the code which is why I haven't merged it yet, as a fyi.

2024-03-05 23:54 UTC, InfusOnWoW commented
Can you try whether the simpler: https://github.com/WeakAuras/LibRangeCheck-3.0/pull/18 works for you?

2024-03-06 17:51 UTC, kodewdle commented
> Can you try whether the simpler: #18 works for you?

it falls back to interact up close but it's `lo` value seems to hit `1` which causes it to fails for a moment in between 8 yards on Hunter: 

https://github.com/WeakAuras/LibRangeCheck-3.0/assets/2266754/ca5aa221-3e57-4cf3-9434-88898209d008

2024-03-06 17:51 UTC, closed without merging

2024-03-07 20:11 UTC, InfusOnWoW commented
Eh, can you describe the problem in more detail? I can't see anything wrong in the video.

2024-03-07 22:38 UTC, kodewdle commented
> Eh, can you describe the problem in more detail? I can't see anything wrong in the video.

in this video, the frame was not supposed to fade at all but around 8 yards it fades.  it's only a guess but i believe that happens because of the function `getRangeWithCheckerList` when it makes it to `elseif lo <= 1 then` because `lo` is `1` and the `min` range is actually the `max` and the `max` is returned as `nil`.  i believe it would happen when the shift from 2 passing spells leads to only 1 passing spell before the interact fallback happens.

2024-03-07 22:53 UTC, InfusOnWoW commented
Right, I know see the target frame fade, can you check what the api actually returns and wherther changing that branch to return instead of guessing?

That branch does indeed look wrong, I guess the code there should be:
```
elseif lo <= 1 then
    if checkerList[1].checker(unit, true) then
        return 0, checkerList[1].range
   else
       return checkerList[1].range, nil
   end
else
```

2024-03-07 23:09 UTC, Flamanis commented
I don't like the idea of checking an extra time when `#checkerList` is even.

2024-03-08 07:46 UTC, InfusOnWoW commented
We need to first figure out what the problem is, before deciding on how to fix that.

2024-03-10 22:06 UTC, InfusOnWoW commented
@kodewdle can you test that suggestion, or give better instructions on how to reproduce that?

2024-03-11 07:10 UTC, Flamanis commented
If this is testing methods for your pr, i would recommend that it stay on your pr. Fragmenting the conversation makes it difficult to follow.

2024-03-11 14:42 UTC, InfusOnWoW commented
It's isn't me who started the discussion here, now that it is here, I want the discussion to stay in one place.

2024-03-15 20:24 UTC, InfusOnWoW commented
The analysis with "lo" hitting 1 is incorrect though, the range checkers are arranged from high to low ranges, so checkerList[1] is the range checker for the longest range. Thus my suggested fix is also obviously incorrect.

Again, I ask how can I easily reproduce the issue? What exactly is the api returning in that case.

If you guys don't start helping in debugging the issue, I'll just merge my PR and wait for a better bug report.

2024-03-23 10:32 UTC, InfusOnWoW commented
I have merged my PR now. If you guys want me to investigate the remaining issue, you need to actually provide information on the circumstances in which the library returns incorrect information. A video showing a problem, without even detailing what the api calls were and what the api returns is not enough.